CREATE SEQUENCE SSN_ID_SEQ
START WITH 100000001
INCREMENT BY 1
MAXVALUE 999999999;

INSERT INTO STATES_MASTER VALUES(1,'Columbus');
INSERT INTO STATES_MASTER VALUES(2,'Texas');
INSERT INTO STATES_MASTER VALUES(3,'California');
INSERT INTO STATES_MASTER VALUES(4,'Florida');
INSERT INTO STATES_MASTER VALUES(5,'Washington');
INSERT INTO STATES_MASTER VALUES(6,'New Jersey');
INSERT INTO STATES_MASTER VALUES(7,'Michigan');